udpated the GIT_USAGE_HOSTED_SKILL_DOCUMENTATION variable
alexa/ask-cli pull request #396
Opened 2021-05-18 10:31 UTC by bbezerra82

*Issue #, if available:* 
[393](https://github.com/alexa/ask-cli/issues/393)
*Description of changes:*
Updated the `GIT_USAGE_HOSTED_SKILL_DOCUMENTATION` variable with a more appropriate one.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-18 16:10 UTC, nikhilym approved these changes

2022-04-28 18:48 UTC, CamdenFoucht commented
Hi @bbezerra82 could you update this PR to rerun these checks? Thank you for the contribution!

2022-04-28 18:51 UTC, CamdenFoucht requested changes
Requesting update to rerun checks 😊

2022-08-04 20:17 UTC, CamdenFoucht commented
Closing in favor of #438

2022-08-04 20:17 UTC, closed without merging